20171224
/*
move to GitHub to keep learning anywhere.

"关于HTTP协议，一篇就够了"https://www.cnblogs.com/ranyonsue/p/5984001.html
"HTTP 协议入门"http://www.ruanyifeng.com/blog/2016/08/http.html
to read
"HTTP协议详解"https://www.cnblogs.com/li0803/archive/2008/11/03/1324746.html
    利用telnet观察http协议的通信过程 //no telnet default in win7, can open from Control Panel/Programs and Features/Turn Windows features on or off/Telnet Client
    easier than by wireshark. tried and fail. wireshark still needed.
"图解HTTP.pdf"
*/
/* git command used today
git clone git@github.com:hongliah/hongliah.git
cd hongliah
git config --local user.name "hongliah"
git config --local user.email hongliang.hu@163.com
touch JS.H //and edit by UltraEdit
git status
git add .
git status
git commit -m "JS.H added"
git status
git push
*/


